<a href="https://colab.research.google.com/github/florang03/datasci_1_loading/blob/main/Coding_exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

**CSV_Dataset 1**:
Information about home infusion therapy providers, as of Sept 8, 2026

**Columns**

**1. Enrollment ID**
*  Contians the dentification number given by CMS, for providers that are in network with medicare.

**2. Buisness Name**

*   Has the names of the practice.

**3. Street Address Line_1**

*  Has the street address of the practice.

**4. Street Address line_2**

*   Has the apartment or suite numbers, if applicable.

**5. City**

*   Has the city in which the practice resides.

**6. State**
* Has the state in which the practice resides.

**7. Zip**
* Has the zip code.

**8. Practice Location Phone Number**
* Contains the contact information for the specialty.

**9. Specialty Name**
* Has the type and specific specialty description.

**10. Geographic Location Type Description**
* Has the geographic description of the practice.

**11. Geographic Location City Name**
* Has the city in which the practice resides, if applicabkle.

**12. Geographic Location State Code**
* Has the state codes in which the practice resides.

**13. Geographic Location Zip Code**
* Has the geographic zip, if applicable.

**14. State County Name**
* Has the count in which the practice resides, if applicable.

In [ ]:
df1 = '/content/Home_Infusion_Therapy_Providers_Sep_08_2026.csv'
read_csv1 = pd.read_csv(df1)
read_csv1.head(11)

,Enrollment ID,Legal Business Name,Street Address Line 1,Street Address Line 2,City,State,ZIP Code,Practice Location Phone Number,Specialty Name,Geographic Location Type Description,Geographic Location City Name,Geographic Location State Code,Geographic Location ZIP Code,State County Name
0,O20201116001628,CRESCENT HEALTHCARE INC,5431 SW 35TH DR,STE 200,GAINESVILLE,FL,32608-5277,(844) 373-8389,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
1,O20250730000500,"KABAFUSION CO, LLC",12450 E ARAPAHOE RD,--,CENTENNIAL,CO,80112-3971,(877) 369-7213,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CO,--,--
2,O20210121000184,I V SOLUTIONS LLC,165 HANSEN CT,STE 106,WOOD DALE,IL,60191-1110,8479454444-1110,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,IL,--,LAKE
3,O20231019000440,PERPETUAL MOBILE MED,5015 EAGLE ROCK BLVD,STE 200,LOS ANGELES,CA,90041-2087,(323) 455-4868,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,CA,--,--
4,O20220203001062,MKARE MANAGEMENT INC,147 AUBURN RDG,--,SPRING BRANCH,TX,78070-6001,(210) 663-1886,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,TX,--,GUADALUPE
5,O20250428002383,INFUPHARMA LLC,1239 NE 8TH AVE,--,FORT LAUDERDALE,FL,33304-2001,(954) 923-3839,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
6,O20260127003422,KABAFUSION TN LLC,2970 SIDCO DR,--,NASHVILLE,TN,37204-3715,(877) 397-8341,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,GA,--,--
7,O20260325003657,AGIOS CORP,1314 S BAY ST,--,EUSTIS,FL,32726-5551,(325) 357-6699,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,FL,--,--
8,O20220509002548,FACTOR ONE SOURCE PHARM LLC,217 GLENN ST,STE 300,CUMBERLAND,MD,21502-2590,(877) 828-3940,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,WI,--,--
9,O20220509002548,FACTOR ONE SOURCE PHARM LLC,217 GLENN ST,STE 300,CUMBERLAND,MD,21502-2590,(877) 828-3940,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,WY,--,--
10,O20220509002548,FACTOR ONE SOURCE PHARM LLC,217 GLENN ST,STE 300,CUMBERLAND,MD,21502-2590,(877) 828-3940,HOME INFUSION THERAPY SUPPLIER,RENDERING AREA,--,AL,--,--

**CSV Dataset_2**:
Information about opiod treatment providers, as of Sept 18, 2026
Columns

**1. NPI**

* Contains the national provider identifier.

**2. Provider Name**

* Contains the name of the practice.

**3. Street Address Line 1**

* Contains the street address of the practice.

**4. Street Address Line 2**

* contains the apartment or suite numbers, if applicable.

**5. City**

*   Has the city in which the practice resides.

**6. State**
* Has the state in which the practice resides.

**7. Zip**
* Has the zip code.

**8. Medicare ID effective Date**

* Contains the date in which the practic's medicare ID is becomes active.

**9. Phone**

* Contains the contact information of the practice.

In [ ]:
df2 = '/content/Opioid_Treatment_Program_Providers_Sep_15_2026.csv'
read_csv2 = pd.read_csv(df2)
read_csv2.head(11)

,NPI,PROVIDER NAME,ADDRESS LINE 1,ADDRESS LINE 2,CITY,STATE,ZIP,MEDICARE ID EFFECTIVE DATE,PHONE
0,1003008301,"CENTER FOR COMMUNITY ALTERNATIVES,",25 CHAPEL ST,STE 701,BROOKLYN,NY,11201-1917,05/01/2024,7188589658
1,1003081399,BAART BEHAVIORAL HEALTH SERVICES IN,617 COMSTOCK RD,STE 5,BERLIN,VT,05602-8498,10/25/2014,8022232003
2,1003081399 1013055110,BAART BEHAVIORAL HEALTH SERVICES IN,617 COMSTOCK RD,STE 5,BERLIN,VT,05602-8498,01/01/2020,8022232003
3,1003150004,AMS OF WISCONSIN LLC,9532 E 16 FRONTAGE RD,STE 100,ONALASKA,WI,54650-6742,01/01/2020,6087830506
4,1003362484,BHG XLII LLC,5715 PRINCESS ANNE RD,NaN,VIRGINIA BEACH,VA,23462-3222,01/01/2020,7579620748
5,1003368945,RTS EDGEWOOD,2205 PULASKI HWY,NaN,EDGEWOOD,MD,21040-1601,10/13/2020,4434569001
6,1003511213,ANCHOR OF HOPE OPIOID TREATMENT PRO,2307 SPRINGLAKE RD,STE 500,FAMERS BRANCH,TX,75234-5876,01/17/2025,4692915288
7,1003571647,METRO TREATMENT OF FLORIDA LP,"1241 BLANDING BLVD, STE 5",NEW SEASON TREATMENT CENTER 21,ORANGE PARK,FL,32065-5908,01/01/2020,9046700820
8,1003581174 1043641293 1063012334 1215593488 12...,CARNEGIE,2828 CARNEGIE AVE,NaN,CLEVELAND,OH,44115-2629,01/01/2020,2168599500
9,1003581174 1043641293 1063012334 1215593488 12...,CMS AKRON,1502 CANTON RD,NaN,AKRON,OH,44312-4043,01/01/2020,2343760500
10,1003581174 1043641293 1063012334 1215593488 12...,ELYRIA,1508 W RIVER RD N,NaN,ELYRIA,OH,44035-2714,01/01/2020,4406478100

**XLS_Dataset 1**: Contains the expenditures per patient


**Columns**

**1. Fiscal Year**

*  Contains the year in which the data was obtained.

**2. priority groups**

*  Contains the expeditures made per priority group (1-8G) per fiscal year.

**3. Non-enrolled Veterans**

*  Contains the expenditures by non enrolled veterans per fiscal year.

**4. Non-Veterans**

*  Contains the expenditures by non veterans per fiscal year.

In [ ]:
df3 = '/content/AvgCost_FINAL2.xlsx'
read_excel1 = pd.read_excel(df3)
read_excel1.head(11)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Average Expenditures1 Per Patient by Healthcar...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fiscal Year,Priority Group,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1,2.0,3.0,4.0,5.0,6.0,7A,7C,8A,8B,8C,8D,8E,8G,Non-enrolled Veterans,Non-Veterans
3,2000,8441,4126.0,3640.0,19448.0,4358.0,2342.0,2108,1822,-,-,-,-,-,-,1210,511
4,2001,8347,4146.0,3723.0,18249.0,4471.0,2223.0,2259,1870,-,-,-,-,-,-,1904,587
5,2002,8719,3986.0,3608.0,17134.0,4583.0,2163.0,2324,1890,-,-,-,-,-,-,1929,595
6,2003,9058,3980.0,3968.0,17083.0,4861.0,2251.0,3793,2922,2124,-,1837,-,1124,1074,2333,674
7,2004,10017,4511.0,4130.0,17286.0,5310.0,2313.0,4474,3221,2468,-,2143,-,795,1153,2538,791
8,2005,10228,4559.0,4215.0,17400.0,5516.0,2280.0,4702,3405,2645,-,2370,-,870,874,2710,1924
9,2006,10515,4678.0,4253.0,17135.0,5669.0,2418.0,4919,3644,2881,-,2389,-,980,1266,-,927
10,2007,10428,4671.0,4300.0,17216.0,5921.0,2394.0,4725,3855,2912,-,2516,-,1029,1778,-,896

**XLS_Dataset 2**: Contains the types and counts of licensed and certified Healthcare Facility Beds


**Columns**

**1. County**

*  Contains the name of the County in which the facility resides.

**2. FAC_FDR**

*  General Acute Care Hospitals: a health facility that has a governing body with overal administrative and professional responsibility

**3. Facility_Count**

* Contains the number of licensed general acute care hospitals.

**4. Bed_Capacity**

* Contains the overall number of licensed bed in a facility.

**5. Acute Psychiatric Care**

* Contains the number of beds licensed for acute psychiatric care.

**6. Acute Respiratory Care**

* Contains the number of beds licensed for acute respiratory care.

**7. Burn**

* Contains the number of bed licensed for burns.

**8. Chemical Dependency Recover**

* Contains the number of bed licensed for chemical dependency recovery.

**9. Coronary Care**

* Contains the number of bed licensed for Coronary Care.

**10. Intesive Care**

* Contains the number of bed licensed for intesive care.

**11. Intensive Care Newborn Nursery**

* Contains the number of bed licensed for intesive care newborn nursery.

**12. Intermediate Care**

* Contains the number of bed licensed for intermediate care.

**13. Labor and Delivery**

* Contains the number of bed licensed for labor and delivery.

**14. Pediatric**

* Contains the number of bed licensed for Pediatrics.

**15. Pediatric Intensive Care Unit**

* Contains the number of bed licensed for pediatric intesive care unit.

**16. Perinatal**

* Contains the number of bed licensed for perinatal.

**17. Rehabilitation**

* Contains the number of bed licensed for rehabilitation.

**18. Renal Transplant**

* Contains the number of bed licensed for renal transplant.

**19. Unspecified Acute Care**

* Contains the number of bed licensed for unspecified acute care.

In [ ]:
df4 = '/content/ca_county_gach_bed_counts.xlsx'
read_excel2 = pd.read_excel(df4, sheet_name=2)
read_excel2.head(11)

,COUNTY_NAME,FAC_FDR,FACILITY_COUNT,BED_CAPACITY,ACUTE PSYCHIATRIC CARE,ACUTE RESPIRATORY CARE,BURN,CHEMICAL DEPENDENCY RECOVERY,CORONARY CARE,INTENSIVE CARE,INTENSIVE CARE NEWBORN NURSERY,INTERMEDIATE CARE,LABOR AND DELIVERY,PEDIATRIC,PEDIATRIC INTENSIVE CARE UNIT,PERINATAL,REHABILITATION,RENAL TRANSPLANT,UNSPECIFIED GENERAL ACUTE CARE
0,ALPINE,GENERAL ACUTE CARE HOSPITAL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,SIERRA,GENERAL ACUTE CARE HOSPITAL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,SUTTER,GENERAL ACUTE CARE HOSPITAL,1,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14
3,MONO,GENERAL ACUTE CARE HOSPITAL,1,17,0,0,0,0,0,2,0,0,0,0,0,2,0,0,13
4,MARIPOSA,GENERAL ACUTE CARE HOSPITAL,1,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18
5,MODOC,GENERAL ACUTE CARE HOSPITAL,2,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20
6,CALAVERAS,GENERAL ACUTE CARE HOSPITAL,1,25,0,0,0,0,0,8,0,0,0,0,0,0,0,0,17
7,LASSEN,GENERAL ACUTE CARE HOSPITAL,1,25,0,0,0,0,0,0,0,0,0,0,0,4,0,0,21
8,SAN BENITO,GENERAL ACUTE CARE HOSPITAL,1,25,0,0,0,0,0,4,0,0,0,0,0,6,0,0,15
9,TRINITY,GENERAL ACUTE CARE HOSPITAL,1,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25
10,INYO,GENERAL ACUTE CARE HOSPITAL,2,29,0,0,0,0,0,4,0,0,0,0,0,5,0,0,20

**XLS_Dataset 2**: Contains number of vetarns per priority groups per fiscal year.


**Columns**


**1. Fiscal Year**

*  Contains the year in which the data was obtained.

**2. priority groups**

*  Contains the number of veterans per priority group (1-8G) per fiscal year.

**3. Non-enrolled Veterans**

*  Contains the number of non enrolled veterans per fiscal year.

**4. Non-Veterans**

*  Contains the number of non veterans per fiscal year.

In [ ]:
df5 = '/content/PriorityGroup_FINAL3 1.xlsx'
read_excel = pd.read_excel(df5)
read_excel.head(11)

,Number of Veteran Patients by Healthcare Priority Group: FY2000 to FY2013,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Number of Veteran Patients by Healthcare Prior...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fiscal Year,Priority Groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Non-enrolled Veterans,Non-veterans
3,NaN,1,2.0,3.0,4.0,5.0,6.0,7A,7C,8A,8B,8C,8D,8E,8G,NaN,NaN
4,2000,441491,264535.0,434690.0,145848.0,1397736.0,48440.0,43626,530890,--,--,--,--,--,--,120669,312810
5,2001,482448,277036.0,478908.0,162026.0,1512410.0,42791.0,45183,782539,--,--,--,--,--,--,60491,305874
6,2002,539792,292323.0,500686.0,156346.0,1542886.0,45304.0,44838,1030202,--,--,--,--,--,--,93707,298269
7,2003,610692,306640.0,520264.0,170869.0,1542874.0,53924.0,4324,106478,43387,--,1068497,--,945,10063,66476,301438
8,2004,662952,313622.0,527330.0,175953.0,1596958.0,70967.0,4604,138563,41550,--,1035910,--,1617,16907,90787,301431
9,2005,720975,326321.0,543246.0,178895.0,1592261.0,99463.0,5641,170328,40309,--,1033437,--,2021,14268,79180,445322
10,2006,768537,342023.0,568740.0,177563.0,1575645.0,134425.0,5948,162130,45519,--,1104720,--,2464,13086,--,288025

**JSON_Dataset 1**: Contians information about medical providers that use cannabis treatment.


**Columns**

**1. County**

*  Contains the county in which the practice resides.

**2. City**

*  Contians the city in which the practice resides.

**3. Name**

*  Contains the name of the provider.

**4. Specialty**

*  Contains the specialty of the practice.

**5. Address**

*  Contains the street address of the practice.

**6. Address 2**

* Contains the apartment or suite number of the practice.

**7. State**

* Contains the state in which the practice resides.

**8. Zip**

* Contains the zip code of where the practice resides.

**9. Phone**

* Contains the contact information of the practice.

**10. NYS Physical Points**

* Contains the coordinates in which the practice resides.

In [ ]:
df6 = '/content/Cannabis.json'
read_json1 = pd.read_json(df6)
read_json1.head(11)

,:id,:version,:created_at,:updated_at,county,city,name,specialty,address,address_2,state,zip,phone,nys_physical_points,:@computed_region_yamh_8v7k,:@computed_region_wbg7_3whc,:@computed_region_kjdx_g34t
0,row-inn6-26ya_6f7p,rv-7phm~7urv~2w8g,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,FAISAL RAFIQ,PSYCHIATRY,1873 WESTERN AVE,SUITE 202,NY,12203,(518) 605-7505,"{'type': 'Point', 'coordinates': [-73.87309, 4...",832.0,40.0,2030.0
1,row-65up_6n9n~9a53,rv-ethe-5ctg_7xpi,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,HANNAH BRANNIGAN,PALLIATIVE CARE,315 S MANNING BLVD,NaN,NY,12208,(518) 525-5064,"{'type': 'Point', 'coordinates': [-73.80456, 4...",814.0,45.0,2030.0
2,row-i7ce-md63~ehwv,rv-u63c.5tfx_p8pb,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,JOSEPH AMENDOLARE,FAMILY PRACTICE,5 COMPUTER DRIVE WEST,SUITE 202,NY,12205,(315) 525-2709,"{'type': 'Point', 'coordinates': [-73.80934, 4...",834.0,42.0,2030.0
3,row-z42i~65ic_85px,rv-rp3s_8dey~ehy5,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,KENNA ELMENDORF-BURNS,PSYCHIATRY,1 PINNACLE PLACE SUITE 102,NaN,NY,12203,(518) 689-0244,"{'type': 'Point', 'coordinates': [-73.83593, 4...",832.0,40.0,2030.0
4,row-5rev_n6jb~4iqe,rv-s5mj.z523.4ef6,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,RACHAEL MASON,RHEUMATOLOGY,4 TOWER DRIVE,FL. 8,NY,12203,(518) 489-4471,"{'type': 'Point', 'coordinates': [-73.8422, 42...",832.0,40.0,2030.0
5,row-s4yr-dp97-nh39,rv-u29v.meps~mm9j,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,KELLEY POWERS,RHEUMATOLOGY,4 TOWER PLACE,8TH FLOOR,NY,12203,(518) 489-4471,"{'type': 'Point', 'coordinates': [-73.8422, 42...",832.0,40.0,2030.0
6,row-yisp_jmcy-mhdz,rv-r6sx.r5h5_q5te,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,BARBARA HILL,FAMILY PRACTICE,1873 WESTERN AVE SUITE 101,NaN,NY,12203,(518) 689-7548,"{'type': 'Point', 'coordinates': [-73.87309, 4...",832.0,40.0,2030.0
7,row-kxmh_w7d3.htvg,rv-6q3w~fm3s-wisp,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,HANI MIDANI,NEUROLOGY,"63 SHAKER ROAD, SUITE 102-104",NaN,NY,12203,(518) 429-2561,"{'type': 'Point', 'coordinates': [-73.74867, 4...",814.0,41.0,2030.0
8,row-egrp-7s27-jwkb,rv-5y7c-qy3r_c7nq,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,GRIFFAN RANDALL,PSYCHIATRY,1809 WESTERN AVENUE,NaN,NY,12203,(518) 655-1590,"{'type': 'Point', 'coordinates': [-73.86722, 4...",832.0,40.0,2030.0
9,row-w9m8.xfad~ds5u,rv-s83r-6t8c-kvex,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,JENNIFER LOGAN,PSYCHIATRY/NEUROLOGY,ALBANYMED,43 NEW SCOTLAND AVE,NY,12208,(802) 236-2611,NaN,NaN,NaN,NaN
10,row-ybeq~3efy~sjp9,rv-fiac.kzjr~5wze,2026-09-18 22:30:59.614000+00:00,2026-09-18 22:31:04.693000+00:00,ALBANY,ALBANY,VIJAY VISHWANATH,CHILD NEUROLOGY,43 NEW SCOTLAND AVENUE,MC 70,NY,12208,(518) 262-1700,"{'type': 'Point', 'coordinates': [-73.77469, 4...",814.0,45.0,2030.0

**JSON_Dataset 2**: Contains the percentages of providers who have or have not gotten the influenze vaccines from 2016 - 2017


**Columns**

**1. Facility Name**

* Contains the name of the medical facility.  

**2. Overall Percent**

*  Contains the percentage of providers that have the vaccine.

**3. Overall Declined Percent**

*  Contains the percentage of providers that declined having the vaccine.

**4. Overall Unknown Percent**

*  Contains the percentage of providers that have not answered.

**5. Icon**

*  Contains a link with an image associated with the organization.

**6. Met HP2020 Goal**

* Contains a yes/no for if the facility has meet the healthy people goal of 2020

**7. Zip Code**

* Contains the zip code in which the facility reside.

**8. Location**

* Contains the address in which the facility resides.

In [3]:
df7 = '/content/HealthcareWorkerVaccinations.json'
read_json2 = pd.read_json(df7)
read_json2.head(11)

,:id,:version,:created_at,:updated_at,facility_name,overall_percent,overall_declined_percent,overall_unknown_percent,icon,met_hp2020_goal,zip_code,location_1,:@computed_region_7u8j_y3re,:@computed_region_ciix_jbrk,:@computed_region_i25a_xk5b
0,row-pcc6.n35g-96r7,rv-kyj8-hpve.w8hn,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Adventist Medical Center,77.1,11.6,11.2,41de192c-3f11-4367-8e8e-ac2e5e85148f,no,97216,"{'latitude': 45.511537, 'longitude': -122.5590...",46.0,23.0,2410.0
1,row-8z5c-m9yj~pc33,rv-jqg5.fmgb.gi77,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Asante Ashland Community Hospital,74.5,16.8,8.7,96499a8d-8521-46f2-851f-b428ba8f61d3,no,97520,"{'latitude': 42.206445, 'longitude': -122.7251...",5.0,3.0,2367.0
2,row-p5zc~wwi8.b5id,rv-nabf.rg32.fzqy,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Asante Rogue Regional Medical Center,71.8,21.1,7.1,4703ddec-13ac-4a6f-b1f1-ef5e0b9e9265,no,97504,"{'latitude': 42.316483, 'longitude': -122.8304...",6.0,3.0,2367.0
3,row-6ceq~umfw_3bx2,rv-a5je~z2fs_5jg8,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Asante Three Rivers Medical Center,74.6,17.7,7.7,8909152b-6936-4b18-b610-f7dc9b6cc12e,no,97527,"{'latitude': 42.420437, 'longitude': -123.3414...",3.0,2.0,2368.0
4,row-mkt9-96ic~hjrs,rv-7sp4.4gat-tpyj,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Bay Area Hospital,74.8,15.7,9.5,8b10b67e-6320-4a90-a455-6c0d7d2a5ae7,no,97420,"{'latitude': 43.385854, 'longitude': -124.2324...",9.0,5.0,2320.0
5,row-3wcw~9bv2~ii5n,rv-gbyh.ye9w.z4f9,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Blue Mountain Hospital,73.8,2.2,24.0,836b5c5a-bfb8-4812-b9b7-7d7309a8fcd5,no,97845,"{'latitude': 44.417651, 'longitude': -118.9592...",60.0,30.0,2365.0
6,row-9gpq.cid2.6xh9,rv-g7h6.nnzp_f4a4,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Cedar Hills Hospital,60.4,20.9,18.7,8c392524-3568-42c2-b9d6-fce84f0b3b9f,no,97225,"{'latitude': 45.506265, 'longitude': -122.7837...",34.0,17.0,724.0
7,row-uz75.35b6.jagc,rv-ganw-qxmk.q52a,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Columbia Memorial Hospital,86.5,13.5,0.0,6af9eb2a-0fd4-45d8-85ba-67ebff2fa45e,no,97103,"{'latitude': 46.188503, 'longitude': -123.8185...",32.0,16.0,2318.0
8,row-45e3_hd87~tmtd,rv-5ezr-vekn~gmji,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Coquille Valley Hospital,56.0,25.7,18.3,26bba059-9a43-482b-9aa3-c7d0db7ead47,no,97423,"{'latitude': 43.178982, 'longitude': -124.1791...",1.0,1.0,2320.0
9,row-xs3a-q83c.x8wk,rv-djqd-ix6t~6icf,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Cottage Grove Community Hospital,87.9,2.6,9.5,7e3d5c96-a4d9-4cfd-9a47-e2cec0c2c163,no,97424,"{'latitude': 43.803841, 'longitude': -123.0386...",7.0,4.0,2371.0
10,row-b3vf-m83r.86br,rv-6fv3-pmm2_73te,2019-09-12 16:25:50.958000+00:00,2019-09-12 16:25:53.006000+00:00,Curry General Hospital,76.0,8.9,15.0,0537fbde-d6ea-4dab-ad3c-58dff5435cb2,no,97444,"{'latitude': 42.411659, 'longitude': -124.4186...",1.0,1.0,2321.0

**JSON_Dataset 3**: Contains Healthcare worker influenza vaccination information for dialysis facilities in 2016 - 2017


**Columns**

**1. Facility Name**

* Contains the name of the medical facility.  

**2. Overall Percent**

*  Contains the percentage of providers that have the vaccine.

**3. Overall Declined Percent**

*  Contains the percentage of providers that declined having the vaccine.

**4. Overall Unknown Percent**

*  Contains the percentage of providers that have not answered.

**5. Icon**

*  Contains a link with an image associated with the organization.

**6. Met HP2020 Goal**

* Contains a yes/no for if the facility has meet the healthy people goal of 2020

**7. Zip Code**

* Contains the zip code in which the facility reside.

**8. Location**

* Contains the address in which the facility resides.

In [4]:
df8 = '/content/query.json'
read_json3 = pd.read_json(df8)
read_json3.head(11)

,:id,:version,:created_at,:updated_at,facility_name,overall_percent,overall_declined_percent,overall_unknown_percent,icon,met_hp2020_goal,location_1,:@computed_region_7u8j_y3re,:@computed_region_ciix_jbrk,:@computed_region_i25a_xk5b
0,row-8zq8_4qta~mfa5,rv-mztz_3udu.ixhv,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,FMC Lebanon,93.3,0.0,6.7,e54d3690-1f09-4404-87b0-4917273e4ade,yes,"{'latitude': 44.54972, 'longitude': -122.90882...",17.0,9.0,2407.0
1,row-uuac_be8c_w7kp,rv-eyyu~iw4h_n2j7,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,PNRS Rose Quarter Dialysis Center,78.4,21.6,0.0,044ef6ec-5a13-4e3f-88b0-0619de6dd81f,no,"{'latitude': 45.558425, 'longitude': -122.6615...",43.0,22.0,2410.0
2,row-7niv~kgdz_5zye,rv-ybha.tgqq~dxur,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,PNRS Tualatin Kidney Center,77.0,5.4,17.6,5e832434-8f6a-492d-b357-986c3b0f1ecc,no,"{'latitude': 45.376328, 'longitude': -122.7582...",37.0,19.0,724.0
3,row-fnpc-sqag~4gry,rv-b2ae-c68e-c3sa,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,USRC East Portland Home Therapies,66.7,33.3,0.0,f141fdf2-bd72-4c50-bb6d-ad751a3a8917,no,"{'latitude': 45.533459, 'longitude': -122.5458...",47.0,24.0,2410.0
4,row-5zt8.ee2f~2uk2,rv-c7sp-r58z~7bbv,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,West Linn Dialysis Center,100.0,0.0,0.0,d60be532-b5f3-4f41-a860-e98f33603acb,yes,"{'latitude': 45.387628, 'longitude': -122.6418...",37.0,19.0,2317.0
5,row-r3xp~wk7s.db9d,rv-si63~dp5r-nx3m,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,Blue Mountain Kidney Center,100.0,0.0,0.0,a3836ca9-506d-4d49-b0c1-cb27f6fd1b97,yes,"{'latitude': 45.643455, 'longitude': -118.6857...",58.0,29.0,2413.0
6,row-dsic-5939_i2ie,rv-dk5j_gus4_scdc,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,Cornell Road,80.6,0.0,19.4,fa8e8692-5467-4d93-8cf1-5b228545a75e,no,"{'latitude': 45.532477, 'longitude': -122.8490...",34.0,17.0,724.0
7,row-cvm9~6reb_5vt9,rv-ami3.czrj~magv,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,FMC Coos Bay,85.1,10.6,4.3,57c4451a-a1e1-457d-a3e8-1b83c204022a,no,"{'latitude': 43.386035, 'longitude': -124.2358...",9.0,5.0,2320.0
8,row-s24a_7zs7.zdb7,rv-527c.f2tv-78h7,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,Tualatin Home,83.3,4.8,11.9,9c925320-414d-4d33-b96b-fcc8bbc33593,no,"{'latitude': 45.378916, 'longitude': -122.7588...",37.0,19.0,724.0
9,row-24u2_am69_8e7h,rv-27m3.396m_k2u4,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,USRC Gresham Dialysis Center,76.9,19.2,3.8,3416f50f-71b0-4b19-8b7d-c92f10ecf452,no,"{'latitude': 45.497996, 'longitude': -122.4175...",50.0,25.0,2410.0
10,row-bxi6_gdpw.irat,rv-5d4i~nbn2-ske9,2019-09-12 16:44:09.758000+00:00,2019-09-12 16:44:12.175000+00:00,USRC Portland Dialysis Center,80.0,8.0,12.0,ed17222a-0f24-446a-aff0-446acd7dcfe6,no,"{'latitude': 45.519014, 'longitude': -122.5542...",47.0,24.0,2410.0